language: swift
osx_image: xcode10.1
xcode_project: Speedway .xcodeproj
xcode_scheme: Speedway Motors iOS Framework
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8

before_install:
- sudo gem install cocoapods
- pod deintegrate
- pod install --repo-update
- xcrun instruments -w 291F3B95-2455-465D-964F-087EF3300AC7 || true
